choco install -y jing
choco install -y lastpass
choco install -y microsoft-teams
choco install -y sourcetree
choco install -y sql-server-management-studio
choco install -y sql-server-express
choco install -y putty.install
choco install -y postman
choco install -y soapui
choco install -y microsoftazurestorageexplorer
choco install -y f.lux